# ============================================= BlobStore Implementation ==================================
# Read https://james.apache.org/server/config-blobstore.html for further details

# Choose your BlobStore implementation: file, s3, postgres.
implementation=s3

# ========================================= Deduplication ========================================
deduplication.enable=true

# ========================================= Compression ========================================
# Включаем алгоритм ZSTD для сжатия писем и аттачей в S3 (Silo).
# ZSTD поддерживается нативно, дает максимальный коэффициент сжатия при минимальной нагрузке на CPU:
compression.enable=true
# Сжимать объекты размером от 4 КБ (ровно 1 кластер ФС; исключает холостой CPU на мелких письмах):
compression.threshold=4K
# Сжимать, если размер уменьшается хотя бы на 5% (коэффициент <= 0.95):
compression.min-ratio=0.95

# ========================================= Encryption ========================================
encryption.aes.enable=false

# ========================================= ObjectStorage on S3 (Silo) =============================================
objectstorage.s3.endPoint=http://127.0.0.1:9000
objectstorage.s3.region=us-east-1
objectstorage.s3.accessKeyId=minioadmin
objectstorage.s3.secretKey=minioadmin

# Default bucket name in Silo
objectstorage.namespace=james-blobs
objectstorage.bucketPrefix=

# S3 HTTP concurrency & memory reading optimization
objectstorage.s3.http.concurrency=200
objectstorage.s3.in.read.limit=45M
objectstorage.s3.read.timeout=30s
objectstorage.s3.write.timeout=30s
objectstorage.s3.connection.timeout=5s

# ============================================ Blobs Exporting ==============================================
blob.export.implementation=localFile
blob.export.localFile.directory=file://var/blobExporting